### ISSUE TITLE
Performance feedback

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_swc#109]
### What happened?

rules_swc is great, but I think the performance of this ruleset could be improved by some tweaks to the action graph it creates. Presently, one action is created per file, which creates immense overhead. Doing a cold build of a large codebase takes 30+ mins when SWC unencumbered could probably eat through it in less than a minute. This appears to be Bazel overhead from spawning so many actions, and them consequently being queued up. For (a) performance and (b) because it didn't appear to add much value, I disabled sandboxing in .bazelrc for SWCTranspile, but needless to say, sandboxing on top is going to further inflate the time taken. I imagine one-action-per-file is also costly from a remote cache / RBE perspective.

After a cold build, incremental build time is superb, but I think it would be just as fast with, say, 5-10 files per action as 1. Perhaps an int attr could be added that specifies how many files will be inputs to each action, with a default that is greater than 1 but not too large either, to enable some economy of scale..

### Version

~

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by alexeagle** [comment]
Hey @matthewjh , the next release removes the NodeJS spawn for each swc action which I think was the majority of the time. Now we spawn the bare rust `swcx` cli which should have excellent cold-start performance.

Could you check whether it seems improved for your use case?

**Comment by matthewjh** [comment]
Thanks @alexeagle. Performance seems much improved by that change. Will close this and re-open if I spot anything else.
