### ISSUE TITLE
[BUG]: Script doesn't check if user has gsed installed

### ISSUE THREAD

**Issue by Aghassi** [aspect-build/rules_swc#121]
https://github.com/aspect-build/rules_swc/blob/d3cdecadd1cdc25a14776bf95c7812318a15e9a3/scripts/mirror_releases.sh#L25

This is a super minor one, but this script will fail if the user doesn't have gsed installed. Consider adding a check and failing fast with install instructions.

**Comment by alexeagle** [comment]
#57 removed the use of sed / gsed from the mirror script.
