### ISSUE TITLE
[Bug]: Sourcemap links are not generated

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_swc#146]
### What happened?

Well, this is a fun one, though for the life of me I have no obvious candidate for why.

```bazel
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@aspect_rules_swc//swc:defs.bzl", "swc")
load("@bazel_skylib//lib:partial.bzl", "partial")

ts_project(
    name = "src",
    srcs = [
        "src.ts",
    ],
    declaration = True,
    transpiler = partial.make(
        swc,
        source_maps = "true",
    ),
    tsconfig = "//:tsconfig",
)
```

Where `src.ts` is

```typescript
console.log(1);
```

Under rules_swc 0.20.2 the generated `src.js` is:

```javascript
console.log(1);


//# sourceMappingURL=src.js.map
```

Whereas under rules_swc 0.21.0 the output is:

```javascript
console.log(1);
```

The sourcemap file is generated, it's just not linked in the JS output.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_swc 0.20.2 and 0.21.0.

Language(s) and/or frameworks involved: TS

### How to reproduce

```shell
See above :)
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by paullewis** [comment]
FWIW if `source_maps` is set to `both` it causes a panic, and if it's set to `inline` it includes a base64 encoded string in the output.

**Comment by alexeagle** [comment]
Hm. You probably saw that 0.21 is a major change, we no longer run the same swc CLI, and we no longer run under the rules_js pathing scheme where sources are copied to the output tree. So it could be a few things - we should start by figuring out if `swcx` (the underlying native cli we use now) does the right thing in a standalone repro.

/cc @realtimetodie who has been making the `swcx` fixes for us 🙏🏻

**Comment by realtimetodie** [comment]
As @alexeagle mentioned, in [v0.21.0](https://github.com/aspect-build/rules_swc/releases/tag/v0.21.0) we switched to the Rust-based SWC CLI.

In the Rust-based SWC CLI, the source maps option either accepts a value of type boolean or string value `inline`. The program panics here

https://github.com/swc-project/swc/blob/ca64ab0906afe22a513f3d2a0614792b86d51293/crates/swc/src/config/mod.rs#L256

Besides, there is the Node.js-based SWC CLI. It uses native napi bindings to Rust and comes with additional features.
For some odd reason, a `sourceMappingURL` is appended to the output file in Node.js only

https://github.com/swc-project/cli/blob/933589ae907637afb7f0b0a43b7a24a7a920595e/src/swc/compile.ts#L31

This should not be the case. I will follow up on this upstream.
For the time being, you can include a //# sourceMappingURL=... comment manually in your source code or use the `inline` option.

Documentation

- https://swc.rs/docs/configuration/compilation#sourcemaps
- An extensive explanation of the source maps option: https://github.com/swc-project/swc/blob/ca64ab0906afe22a513f3d2a0614792b86d51293/node-swc/src/types.ts#L569-L579

**Comment by realtimetodie** [comment]
please assign this to me

**Comment by alexeagle** [comment]
@realtimetodie any update on upstream changes? Do you have an issue/PR on swc yet?

I imagine we could workaround this in rules_swc with another action to add the missing line on the end of JS files, though of course that's a performance penalty adding another action that has to run after swc.

I think this is the last issue we need to resolve before shipping a 1.0, just FYI

**Comment by realtimetodie** [comment]
@alexeagle I'm about to finish it

https://github.com/swc-project/swc/compare/main...realtimetodie:swc:feat-source-mapping-url?expand=1

**Comment by realtimetodie** [comment]
@alexeagle I'm about to finish it

https://github.com/swc-project/swc/compare/main...realtimetodie:swc:feat-source-mapping-url

**Comment by realtimetodie** [comment]
https://github.com/swc-project/swc/pull/6873 was merged. I am waiting for a new SWC cli binary release. I will open a new PR to update the version.
