### ISSUE TITLE
[Bug]: sourcemap paths are not relative

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_swc#166]
### What happened?

When we changed to `swcx` we changed the sourcemaps:

https://github.com/aspect-build/rules_swc/blob/main/examples/rc/src/expected.js.map
`"sources":["examples/rc/src/in.ts"]`
https://github.com/aspect-build/rules_swc/blob/v0.20.1/examples/rc/src/expected.js.map
`"sources":["in.ts"]`

### Version

It changed in the commit where we switched from @swc/cli (the nodejs wrapper) to swcx
[https://github.com/aspect-build/rules_swc/commit/6358e06ac2a8d6aca2c2ea0cd6ea9dc7b9217a27#diff-90f27955a28ad20f91303a[…]4c55c9ef8b0ccb3255a1bdd1f726](https://github.com/aspect-build/rules_swc/commit/6358e06ac2a8d6aca2c2ea0cd6ea9dc7b9217a27#diff-90f27955a28ad20f91303a02b1644dfcde3f4c55c9ef8b0ccb3255a1bdd1f726)

**Comment by alexeagle** [comment]
Note, this is pretty typical under Bazel since tools are run in a working directory at the repository root.

Options:
1. change `swcx` to relativize source paths in the sourcemap output
2. compose with another action to post-process the output of `swcx`
3. wrap `swcx` to run it from a different working directory than Bazel spawn the action

**Comment by alexeagle** [comment]
@realtimetodie any ideas on whether option 1 is feasible?

**Comment by alexeagle** [comment]
Maybe it's just that we need `source_root` which is listed as missing on https://github.com/swc-project/swc/issues/4017

**Comment by realtimetodie** [comment]
Yes, the source_root option is not implemented in the Rust-based SWC cli. In the Node.js @swc/cli, where the entire source map is reparsed as JSON again, see https://github.com/swc-project/swc/issues/1388. I mentioned this bug in https://github.com/aspect-build/rules_swc/pull/154#issuecomment-1409109080.

https://github.com/swc-project/cli/blob/461231917181133fd2e98b954fce07b599711502/src/swc/compile.ts#L20

https://github.com/swc-project/cli/blob/461231917181133fd2e98b954fce07b599711502/src/swc/util.ts#L58-L59

I will look into it this weekend

**Comment by alexeagle** [comment]
Ping @realtimetodie have any time to look? If not maybe @titanous who contributed another swc fix?

**Comment by realtimetodie** [comment]
Yes, I'm about to complete it. I have some more time tomorrow.

**Comment by realtimetodie** [comment]
The changes were merged upstream. I added an example in https://github.com/realtimetodie/rules_swc/tree/bug-166

**Comment by alexeagle** [comment]
@realtimetodie user question on this that I'm not sure how to answer: https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1677624490464619?thread_ts=1675968328.558779&cid=CEZUUKQ6P

**Comment by realtimetodie** [comment]
So I went back in the history to test the behaviour when rules_swc used the Node.js @swc/cli.

In general, the `sourceRoot` value is not set by default. However, in rules_swc we set a path by default now. I think this is wrong. There should be no `sourceRoot` value set by default. We can't possibly assume the right path. Every project is different and the `sourceRoot` value could also be an URL. 

Instead, the user should to set the sourceRoot value explicitly by either a) by using the --source-root option as a custom argument, or b) we define a new optional variable in the rule `source_root`. This would follow the default swc behaviour.

Example

```
swc(
    name = "compile",
    source_maps = True,
    source_root = "./path/to",
)
```

https://github.com/swc-project/cli/blob/df9b9ec04201ac353c3e794fed6fc29152fc4cb0/src/swc/options.ts#L221

@alexeagle Let me know what you think

**Comment by realtimetodie** [comment]
The same goes for the source file name, which is the first entry in the `sources` JSON array using the --source-file-name option.

Example

```
swc(
    name = "compile",
    source_maps = True,
    source_file_name = "custom.ts",
)
```

https://github.com/swc-project/cli/blob/df9b9ec04201ac353c3e794fed6fc29152fc4cb0/src/swc/options.ts#L220

**Comment by alexeagle** [comment]
TAL at #176 which aligns the behavior with `ts_project`

**Comment by alexeagle** [comment]
Seems like the mistake was just that the source-root should have been relative to the rootDir.
