### ISSUE TITLE
swc starts failing in RBE after v0.5.1

### ISSUE THREAD

**Issue by danigar** [aspect-build/rules_swc#38]
Building typescript srcs using `ts_project` rule with swc transpiler fails in RBE mode since swc version `0.5.1` (also tested with the latest release `v0.7.0`). Local sandbox execution is successfull.

Prior to `v0.5.0`, swc RBE transpilation worked just fine with the same config.

The output stack trace of the error is:

```
Error: Cannot find module 'slash'
Require stack:
- /var/lib/../exec/bazel-out/exec/bin/external/aspect_rules_swc/swc/node_modules/@swc/cli/lib/swc/dir.js
```
It looks like in RBE mode executors cannot resolve npm dependencies required by swc cli.
I've checked that `slash` package can be found in `/var/lib/../exec/bazel-out/exec-EAxs2/bin/external/aspect_rules_swc/swc/node_modules/.aspect_rules_js`.

## Repro
I've created a test case repository to show all the config that makes it fail.

https://github.com/danigar/bazel-swc-lab

**Comment by alexeagle** [comment]
I think this is another case of https://github.com/bazelbuild/bazel/issues/10298
rules_js switched to pnpm under the hood, and it relies on symlinks into an npm package virtual store.

**Comment by alexeagle** [comment]
For SWC specifically the best fix is to simply stop depending on the node.js `@swc/cli` package, and thus rules_js. We only need the pure-rust CLI.

So https://github.com/aspect-build/rules_swc/pull/57 could fix this.

**Comment by alexeagle** [comment]
#57 still seems hard, there are some missing things in the rust CLI.

Separately, the fix for RBE in rules_js is making progress today :)

**Comment by alexeagle** [comment]
update: latest rules_js release has RBE support. I'm still working on #57
