### ISSUE TITLE
Update SWC to re-enable sandbox

### ISSUE THREAD

**Issue by bazaglia** [aspect-build/rules_swc#61]
Now that https://github.com/swc-project/swc/issues/4057 has been closed, if the SWC binary being used by rules_swc is updated to v1.2.218, it should be possible to remove the flag that disables the sandbox:

https://github.com/aspect-build/rules_swc/blob/29f5a69ec3636920d11c33576f2dc2d295be7a01/.bazelrc#L6-L8

**Comment by alexeagle** [comment]
I took a stab at this: https://github.com/aspect-build/rules_swc/pull/97/files#r1000754748

but seems like there's still an SWC bug :(

**Comment by realtimetodie** [comment]
I'm working on this

**Comment by alexeagle** [comment]
Looks like we're just waiting on the next SWC release and we can fix this.
It doesn't need to be a breaking change, we just document that users still have to use the workaround if their swc version is less than X

**Comment by alexeagle** [comment]
fixed in #57
